### ISSUE TITLE
Example code is now working on windows

### ISSUE THREAD

**Issue by TreLosOyk** [ceyzeriat/joystick#2]
I am pretty sure that everything is imported correctly BUT
when trying to excecute the windows that pop-up dont seem to be responding....

**Comment by ceyzeriat** [comment]
Can you give more details about the execution?
How are you running the code? (ipython, console, spyder, ...)
What do you mean no response? no updating nor movement whatsoever, or no update once you change some settings (i.e. xylim, xnpts, ...)
Any error message or warning?
Did you try to run a minimalist example (just 1 frame) to see how it behaves?

**Comment by ceyzeriat** [comment]
If no additional information is provided, I will consider this issue closed on Friday.
