### ISSUE TITLE
Can you add a save figure function in the current framework?

### ISSUE THREAD

**Issue by hjchai** [ceyzeriat/joystick#3]
Please correct me if I miss something here. I didn't see that there is a function to save a frame to figure. I know this package is used for monitoring. However, providing an option to save the plot at a certain time is handy, especially at some checkpoint.

Oh, BTW, awesome work! Really good monitoring tool. Well documented as well!

**Comment by ceyzeriat** [comment]
Thanks! I'm happy to read that the package is useful :)

You are right, there is no save/record option. I also think that it would be a nice addition to the package.

I'll try to understand your request better:
- are you thinking of a function to save an image/figure/video to a file?
- do you mean to access the frame as a matplotlib "figure" object in the console?

**Comment by hjchai** [comment]
Thank you @ceyzeriat for replying my request so quickly!

I am thinking something like this:
t = test()
t.start()
"At certain time point(or at the end of the monitoring), we can call t.save() to save any particular plot in image/figure/video format" - (video may require a start time and an end time for recording)
t.save()

So far, I didn't find a way to save a plot in console. I can only use a screenshot tool to capture the monitoring result which is not very convenient.

Another question: can I invoke the plotting frame outside python console? Now I can only manually start the monitoring by typing t=test(), then t.start() in ipython console. If I can invoke these two commands in my simulation code, the monitoring window will automatically appear when simulation starts to run. This will save a lot of effort especially when one needs to run many sets of simulations. I am not sure if the current code supports this. Would you give me some advice?

Thanks.

**Comment by ceyzeriat** [comment]
Ok ok I see
I am replying quickly from my phone and partly from memory.. just warning you in case thia doesn't work :)

There might be a tweak you can use that give you a quick and dirty result before I get the code sorted on the saving.
Say you have a simulation t = test() with a graph frame stored in t.mygraph
You can access the matplolib figure this way:
t.mygraph._fig
And use the standard matplolib method to save it to a file:
t.mygraph._fig.savefig('plot.png') # you can change the extension to pdf and will get a pdf instead
Thats should get you started with the saving - not a video though, only the graph as it looks at the time you invoke the savefig method.

For the many-simulation part I think you could write a script in myscript.py:
###
import joystick
(...)
t1 = test1()
t2 = test2()
(...)
t1.start()
t2.start()
(...)
###
And in a ipython console you should be able to type
run myscript
The whole content of the myscript.py file will be executed in the current console and all variables accessible in the namespace: you can type t1.stop() anytime for example to keep a hand on the simulations.
Note that you can have 1 joystick object (t = test()) with several frames and input data-feeds, you don't have to create 1 joystick object per graph and have t1,t2,t2,... to launch and manage

Let me know how thia is doing

**Comment by hjchai** [comment]
@ceyzeriat Sorry I didn't get back to your message in time. Was out of town for a conference in the last few days.

Just tested your suggestion in your last post, t.mygraph._fig.savefig('plot.png') works great! It solves my problem for the moment. I'll look forward to seeing your final fix to the code on the 'save' function in the future. Thank you for the wonderful work! I even shared your repository with my co-workers. They were amazed to see such a handy tool to monitor a dynamic output. We used to spend a lot of effort to make things work in a similar way, but much much uglier than yours.

Finally, maybe this is a dumb question. Like I asked in the my last post, is it able to use the library in some other python code instead of starting monitoring in a ipython console? I got a simulation running, and want to automatically start joystick monitoring script after simulation starts. Is it possible to do so?

**Comment by ceyzeriat** [comment]
Great!
Happy to read this lib is useful :)
If you have other features in mind it would be great to share and see what could be included in the package.

The joystick simulation "t" is like any other object so you can initialize it and start it from another class/script.
The only known limitation is that it is interactive (i.e. non-blocking) so you cant run it in a terminal using "python myscript.py", you will have to use the "-i" option to make it interactive.
There are some incompatibilities with IDEs as they often add another layer of interactivity which clashes with the non-blocking nature of joystick, but that should be it.
Cheers
Ps: can you leave the issue open until I add the save code so it acts as a reminder? ;)

**Comment by hjchai** [comment]
Thank you so much for the quick response! I'll leave this issue open till you get a chance to fix the code. 

Also, if I understand you correctly, users can design their own plotting class (say I call it ``plot.py``) just like the example you provided in the README, which has a ``t = test()`` and ``t.start()`` at the end of the class to initialize and start the object ``t``. In order to **invoke** this plotting class, I can't use ``python plot.py`` to start the script, but have to either use ``python -i plot.py`` or ``ipython`` and then ``run plot.py``. Right? This looks a little promising to me now, though not ideal.

The reason I am asking about this is that my simulation is running in an environment written in C++. My ideal scenario will be somewhere in my C++ code it will start the ``plot.py`` script. May be I'll do some research to see if it is possible to invoke the command ``python -i plot.py`` inline of my C++ code.

**Comment by ceyzeriat** [comment]
"use python -i plot.py or ipython and then run plot.py. Right?"
Thats right.
Although the -i line will become blocking in your c++ I imagine. You could try without and see. Maybe as long as C++ is running the python threads are kept alive.
It looks like you only need monitoring, not controlling?
Never tried to call python from C++ so you'll have to dig yourself on this :)

**Comment by hjchai** [comment]
Thank you for confirming. 

Yes, I do only need monitoring. Don't need to change xylim/update_freq and stuff. Does that may thing easier or different? Can I run plot.py using 'python plot.py' in a non-interactive session if I don't need the controlling features?

**Comment by ceyzeriat** [comment]
If you did not need controlling you could have gone for another librarie that is blocking in its design, so you would not need the "-i".
Changing xylim or display frequency or not would not change the nature of interactivity.
Just try it out.. I have never tried running C++/python code the way you need it.
If you need monitoring then you will need to have some access to a python terminal where the the simulation is going.
Maybe what you need is a bash script that starts both C++ and python.
Cheers

**Comment by hjchai** [comment]
Sure, I'll dig into that next. 

Can you share which library you are talking about that is blocking in its design? I may give that a try as well.

**Comment by ceyzeriat** [comment]
I don't know such library, I was just thinking of a podsible option - only used joystick ;)

**Comment by hjchai** [comment]
Thank you. I'll work with joystick to see if it is possible to run with C++.

**Comment by ceyzeriat** [comment]
Hi,
I created the savefig method to save the figure as it is showed at the time of call, so this should fixed now
How did things go in the end?
Cheers

**Comment by alberto-battistel** [comment]
Hi,

thanks.

But now I am totally puzzled.

I played around quite a bit with ipython, python, and spyder and I have 
reinstalled everything.

but now if I try to install joystick from pip or pip3 I get an error

Collecting joystick
   Using cached joystick-0.3.6.tar.gz
     Complete output from command python setup.py egg_info:
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-build-ia4n6zcz/joystick/setup.py", line 39, in 
<module>
         + open("HISTORY.rst").read(),
     FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'

     ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in 
/tmp/pip-build-ia4n6zcz/joystick/

This was not happening before...


Alberto

**Comment by ceyzeriat** [comment]
It is fixed.
The package uploader changed and the way to include package data (HISTORY.rst) apparently changed with it, hence the issue not finding it.
Cheers
